// crates/a2a-types/build.rs
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let schema_path = Path::new("schema/a2a.json");

    println!("cargo:rerun-if-changed=schema/a2a.json");

    let schema_content = fs::read_to_string(schema_path)
        .expect("Failed to read schema file");

    let schema: schemars::schema::RootSchema = serde_json::from_str(&schema_content)
        .expect("Failed to parse JSON schema");

    let mut settings = typify::TypeSpaceSettings::default();
    settings.with_derive("Clone".to_string());
    settings.with_derive("Debug".to_string());
    settings.with_derive("PartialEq".to_string());

    let mut type_space = typify::TypeSpace::new(&settings);
    type_space
        .add_root_schema(schema)
        .expect("Failed to process schema");

    let tokens = type_space.to_stream();
    let contents = format!(
        "// Generated by build.rs - do not edit\n\n{}",
        tokens
    );

    let dest_path = Path::new(&out_dir).join("generated_types.rs");
    fs::write(&dest_path, contents).expect("Failed to write generated types");
}
